
output: binary

seed: 0
num_repeats: 20
sensitive_predictor: False

models:
  SVM:
    param:
      nu: [0.05, 0.01, 2] # [grid_start, grid_end, num_grids]
    log_exp_grid: False
  FERM:
    param:
      nu: [0.05, 0.01, 2]
    log_exp_grid: False
  DM:
    param:
      c: [1e-3, 10., 11]
    log_exp_grid: False
  GF:
    param:
      lam: [1e-3, 10., 11]
    log_exp_grid: True
  IF:
    param:
      lam: [1e-3, 10., 11]
    log_exp_grid: True
  SD:
    param:
      lam: [1e-3, 10., 11]
    log_exp_grid: True
  SP:
    param:
      c: [0.1, 0.9, 10]
    log_exp_grid: False
  BGL:
    param:
      c: [0.1, 0.9, 10]
    log_exp_grid: False
  FGLM:
    param:
      lam: [1e-3, 10., 11]
    log_exp_grid: True
  GLM:
    param:
      lam: [0., 0., 0]
    log_exp_grid: False
