
output: continuous

seed: 0
num_repeats: 20
sensitive_predictor: False

models:
  GF:
    param:
      lam: [1e-3, 10., 11]
    log_exp_grid: True
  IF:
    param:
      lam: [1e-3, 8., 11]
    log_exp_grid: True
  HSIC:
    param:
      lam: [1e-3, 0.5, 11]
    log_exp_grid: True
  BGL:
    param:
      c: [0.1, 0.9, 10]
    log_exp_grid: False
  GFERM:
    param:
      eps: [50, 200., 11]
    log_exp_grid: False
  FGLM:
    param:
      lam: [1e-3, 8., 11]
    log_exp_grid: True
  GLM:
    param:
      lam: [0., 0., 0]
    log_exp_grid: False
